name: Build release

on:
  push:
      branches: [ "omnetpp-6.x" ]
  workflow_dispatch: # allows manual execution

jobs:
  build_release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'omnetpp-6.x'

    - name: helloworld
      run:
        echo 'XXXX'

    - name: dockertest
      run: docker --version

    - name: copy
      uses: docker://fedora:latest
      with:
        args: 
          sh -c "ls && cp configure.user.dist configure.user && ls && 
             source setenv &&
             ./configure WITH_LIBXML=yes WITH_QTENV=yes WITH_OSG=yes WITH_OSGEARTH=no"