name: Build release

on:
  push:
    branches: ["omnetpp-6.x"]
  workflow_dispatch: # allows manual execution

jobs:
  # build_release:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v4
  #     with:
  #       ref: 'omnetpp-6.x'

  #   - name: helloworld
  #     run:
  #       echo 'XXXX'

  #   - name: dockertest
  #     run: docker --version

  #   - name: docker run
  #     uses: addnab/docker-run-action@v3
  #     with:
  #       image: fedora:latest
  #       options: -v ${{ github.workspace }}:/omnetpp
  #       shell: bash
  # run: |
  #   echo 'XXXX'

  #   find -name omnetpp

  #   ls

  #   cd omnetpp

  #   ls

  #   cp configure.user.dist configure.user

  #   . setenv

  #   ./configure WITH_LIBXML=yes WITH_QTENV=yes WITH_OSG=yes WITH_OSGEARTH=no

  #   make
  # build_releng:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v4
  #     with:
  #       ref: 'omnetpp-6.x'
  #   - name: build-ide
  #     run: |
  #       cd releng

  #       ./build-omnetpp-ide-linux

  build_ide:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: "omnetpp-6.x"
      - name: build-ide
        run: |
          cd releng
          ./build-omnetpp-in-docker
      - name: upload releases
        uses: actions/upload-artifact@v4
        with:
          path: |
            ${{ github.workspace }}/releng/dist/
          if-no-files-found: ignore

  build-linux:
    needs: build_ide
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
      - name: Display structure of downloaded files
        run: ls -R

      - name: get linux release
        uses: actions/download-artifact@v4
        with:
          pattern: *.linux*.tgz