name: Build release

on:
  push:
    branches: ["omnetpp-6.x"]
  workflow_dispatch: # allows manual execution

jobs:
  # build_release:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v4
  #     with:
  #       ref: 'omnetpp-6.x'

  #   - name: helloworld
  #     run:
  #       echo 'XXXX'

  #   - name: dockertest
  #     run: docker --version

  #   - name: docker run
  #     uses: addnab/docker-run-action@v3
  #     with:
  #       image: fedora:latest
  #       options: -v ${{ github.workspace }}:/omnetpp
  #       shell: bash
  # run: |
  #   echo 'XXXX'

  #   find -name omnetpp

  #   ls

  #   cd omnetpp

  #   ls

  #   cp configure.user.dist configure.user

  #   . setenv

  #   ./configure WITH_LIBXML=yes WITH_QTENV=yes WITH_OSG=yes WITH_OSGEARTH=no

  #   make
  # build_releng:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v4
  #     with:
  #       ref: 'omnetpp-6.x'
  #   - name: build-ide
  #     run: |
  #       cd releng

  #       ./build-omnetpp-ide-linux

  # build-ide:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         ref: "omnetpp-6.x"
  #     - name: build ide
  #       run: |
  #         echo ${{ github.run_id }}
  #         cd releng
  #         ./build-omnetpp-in-docker
  #     - name: upload releases
  #       uses: actions/upload-artifact@v4
  #       with:
  #         path: |
  #           ${{ github.workspace }}/releng/dist/
  #         if-no-files-found: ignore
  #         retention-days: 1

  build-ide:  # for debugging
    runs-on: ubuntu-latest

    steps:
      - uses: dawidd6/action-download-artifact@v6
        with:
          run_id: 11159647668
      - name: list
        run: |
          ls -R
      - uses: actions/cache@v4
        id: cache
        with:
          path: |
            ./artifact
          key: ${{ hashFiles('./artifact/**') }}
      - name: upload linux-x86_64
        uses: actions/upload-artifact@v4
        with:
          name: linux-x86_64
          path: |
            ${{ github.workspace }}/artifact/*linux-x86_64*
          if-no-files-found: ignore
          retention-days: 10
      - name: upload macos-aarch64
        uses: actions/upload-artifact@v4
        with:
          name: macos-aarch64
          path: |
            ${{ github.workspace }}/artifact/*macos-aarch64*
          if-no-files-found: ignore
          retention-days: 10
      - name: upload windows-x86_64
        uses: actions/upload-artifact@v4
        with:
          name: windows-x86_64
          path: |
            ${{ github.workspace }}/artifact/*windows-x86_64*
          if-no-files-found: ignore
          retention-days: 10

  build-ubuntu:
    needs: build-ide
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        name: Download release
        with:
          pattern: "*linux-x86_64*"
      - name: Display structure of downloaded files
        run: ls -R
  
      - name: Install release
        run: |
          cd linux-x86_64
          tar -xf *linux-x86_64.tgz
          cd omnetpp-6.1
          sudo apt update
          ./install.sh -y
          source setenv
          cd samples/aloha
          ./aloha -u Cmdenv -c PureAloha1 --sim-time-limit=10s

  build-fedora:
    needs: build-ide
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        name: Download release
      - name: Install release
        uses: addnab/docker-run-action@v3
        with:
          image: fedora:latest
          options: -v ${{ github.workspace }}:/omnetpp
          shell: bash
          run: |
            cd omnetpp/artifact
            tar -xf *linux-x86_64.tgz
            cd omnetpp-6.1
            ./install.sh -y
            source setenv
            cd samples/aloha
            ./aloha -u Cmdenv -c PureAloha1 --sim-time-limit=10s

  build-arch:
    needs: build-ide
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        name: Download release
      - name: Install release
        uses: addnab/docker-run-action@v3
        with:
          image: archlinux:latest
          options: -v ${{ github.workspace }}:/omnetpp
          shell: bash
          run: |
            cd omnetpp/artifact
            tar -xf *linux-x86_64.tgz
            cd omnetpp-6.1
            pacman -Syy
            ./install.sh -y
            source setenv
            cd samples/aloha
            ./aloha -u Cmdenv -c PureAloha1 --sim-time-limit=10s

  build-opensuse:
    needs: build-ide
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        name: Download release
      - name: Install release
        uses: addnab/docker-run-action@v3
        with:
          image: opensuse/tumbleweed:latest
          options: -v ${{ github.workspace }}:/omnetpp
          shell: bash
          run: |
            cd omnetpp/artifact
            tar -xf *linux-x86_64.tgz
            cd omnetpp-6.1
            zypper refresh
            ./install.sh -y
            source setenv
            cd samples/aloha
            ./aloha -u Cmdenv -c PureAloha1 --sim-time-limit=10s

  build-almalinux:
    needs: build-ide
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        name: Download release
      - name: Install release
        uses: addnab/docker-run-action@v3
        with:
          image: almalinux:9
          options: -v ${{ github.workspace }}:/omnetpp
          shell: bash
          run: |
            cd omnetpp/artifact
            tar -xf *linux-x86_64.tgz
            cd omnetpp-6.1
            ./install.sh -y --no-3d
            source setenv
            cd samples/aloha
            ./aloha -u Cmdenv -c PureAloha1 --sim-time-limit=10s

  build-debian:
    needs: build-ide
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        name: Download release
      - name: Install release
        uses: addnab/docker-run-action@v3
        with:
          image: debian:latest
          options: -v ${{ github.workspace }}:/omnetpp
          shell: bash
          run: |
            cd omnetpp/artifact
            tar -xf *linux-x86_64.tgz
            cd omnetpp-6.1
            apt update
            ./install.sh -y
            source setenv
            cd samples/aloha
            ./aloha -u Cmdenv -c PureAloha1 --sim-time-limit=10s

  build-macos:
    needs: build-ide
    runs-on: macos-14

    steps:
      - uses: actions/download-artifact@v4
        name: Download release
      - name: Install release
        run: |
          cd artifact
          tar -xf *macos-aarch64*.tgz
          cd omnetpp-6.1
          ./install.sh -y
          source setenv
          cd samples/aloha
          ./aloha -u Cmdenv -c PureAloha1 --sim-time-limit=10s

  build-windows:
    needs: build-ide
    runs-on: windows-latest

    steps:
      - uses: actions/download-artifact@v4
        name: Download release
      - uses: msys2/setup-msys2@v2
        name: Setup MSYS
        with:
          install: >-
            unzip
      - shell: msys2 {0}
        name: Install release
        run: |
          cd artifact
          # 7z x *windows-x86_64*.zip
          unzip *windows-x86_64*.zip
          cd omnetpp-6.1
          # .\mingwenv.cmd -c "./install.sh -y && . setenv && cd samples/aloha &&./aloha -u Cmdenv -c PureAloha1 --sim-time-limit=10s"
          ./install.sh -y && . setenv && cd samples/aloha &&./aloha -u Cmdenv -c PureAloha1 --sim-time-limit=10s