name: Build release

on:
  push:
      branches: [ "omnetpp-6.x" ]

jobs:
  build_release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'omnetpp-6.x'

    - name: helloworld
      run:
        echo 'XXXX'